import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from './providers'
import { Suspense } from "react";   // added
import Link from 'next/link'
import { signOut } from './actions/signOut'


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-background text-foreground">
        <header className="border-b">
          <nav className="max-w-5xl mx-auto flex items-center gap-4 p-3">
            <Link href="/dashboard">Dashboard</Link>
            <Link href="/catalog">Catalog</Link>
            <Link href="/visualize">Visualize</Link>

            <form action={signOut} className="ml-auto">
              <button className="text-sm text-muted-foreground hover:underline">
                Sign out
              </button>
            </form>
          </nav>
        </header>
        <Suspense fallback={null}>
        <Providers>
          {children}
        </Providers>
        </Suspense>
      </body>
    </html>
  );
}